server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: bookManagement
          uri: http://localhost:8081
          predicates:
            - Path=/bookManageSystems/** 
        - id: bookRental
          uri: http://localhost:8082
          predicates:
            - Path=/bookRentalSystems/** 
        - id: view
          uri: http://localhost:8083
          predicates:
            - Path= /bookLists/**
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/pointSystems/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: bookManagement
          uri: http://bookManagement:8080
          predicates:
            - Path=/bookManageSystems/** 
        - id: bookRental
          uri: http://bookRental:8080
          predicates:
            - Path=/bookRentalSystems/** 
        - id: view
          uri: http://view:8080
          predicates:
            - Path= /bookLists/**
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/pointSystems/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
